# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oa-vkontakte_alexandrov}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Alexandrov"]
  s.date = %q{2011-02-17}
  s.description = %q{Include this gem into your project with OmniAuth gem and you will get VKontakte login in one line of code.}
  s.email = %q{igor.alexandrov@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/oa-vkontakte.rb",
    "lib/omniauth/strategies/vkontakte.rb",
    "lib/omniauth/strategies/vkontakte/view_helper.rb",
    "lib/omniauth/vkontakte.rb",
    "oa-vkontakte.gemspec",
    "spec/oa-vkontakte_spec.rb",
    "spec/omniauth/strategires/vkontakte_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/igor-alexandrov/oa-vkontakte}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{VKontakte OmniAuth module with view helpers}
  s.test_files = [
    "spec/oa-vkontakte_spec.rb",
    "spec/omniauth/strategires/vkontakte_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oa-core>, [">= 0.2.0.beta4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<oa-core>, [">= 0.2.0.beta4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<oa-core>, [">= 0.2.0.beta4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

